### ISSUE TITLE
Bug or undocumented behavior regarding mixing runtime variables and variables from templates ? 

### ISSUE THREAD

**Issue by DjebbZ** [MicrosoftDocs/azure-devops-yaml-schema#104]
Hello,

I stumbled across a very weird bug or undocumented behavior.

I was trying to add a runtime variable to the list of variables in a stage, and it silently skipped the stage until I moved the runtime variable declaration _after_ the inclusion of templates. The example below will make this clearer.

For context, we have several apps from a mono repo, and I want to release an app only if it actually changed.

``` yml
# non-relevant properties omitted for brevity

# this version never worked and the stage was always silently skipped with no output
- stage: release_app_x
  dependsOn: prepare
  variables:
    # Here I expose an output variable from a previous stage...
    - name: apps
      value: $[ dependencies.prepare.outputs['prepare_job.ListApps.apps'] ]
    - template: ../variables/somefile.yml
    - template: ../variables/anotherfile.yml
  # ...to use it here to run the stage conditionally
  condition: contains(variables.apps, 'app_x')
  jobs:
  # ...

# this version works, and the only change is that the runtime variable is _after_ the `template:` statements
- stage: release_app_x
  dependsOn: prepare
  variables:
    - template: ../variables/somefile.yml
    - template: ../variables/anotherfile.yml
    # Variable moved _after_ the `template:` statements
    - name: apps
      value: $[ dependencies.prepare.outputs['prepare_job.ListApps.apps'] ]
  condition: contains(variables.apps, 'app_x')
  jobs:
  # ...
```

The docs states:

> [...] but you can combine `name`, `group`, and `template` when using list syntax.

Is it expected behavior that `template` must come before `name` ? Is it a bug ?

--edit: we verified that the `apps` variable didn't exist in the `templates` in case of a shadowing, it doesn't.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0029948d-6054-90c7-1dd1-450177589741
* Version Independent ID: 0029948d-6054-90c7-1dd1-450177589741
* Content: [variables definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/variables?view=azure-pipelines)
* Content Source: [content/variables.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/variables.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@DjebbZ I can't reproduce the issue that you are having (I was attempting to build a complete running repro that I could submit to the product team) Can you take a look and let me know if I have missed something (your example doesn't show the initial stage that yields the output variable so maybe I have gotten it a little bit wrong?)

```
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - bash: echo "##vso[task.setvariable variable=s1output;isOutput=true]app_x present"
      name: Bash1
    - bash: echo $(Bash1.s1output)

- stage: Stage2
  dependsOn: Stage1
  variables:
  - template: variables_template_1.yml
  - template: variables_template_2.yml
  - name: apps
    value: $[ dependencies.Stage1.outputs['Job1.Bash1.s1output'] ]
  condition: contains(variables.apps, 'app_x')
  jobs:
  - job: Stage2Job1
    steps:
    - bash: echo "$(varT1) - $(varT2)"
    - bash: echo $(apps)

- stage: Stage3
  dependsOn: Stage1
  variables:
  - name: apps
    value: $[ dependencies.Stage1.outputs['Job1.Bash1.s1output'] ]
  - template: variables_template_1.yml
  - template: variables_template_2.yml
  condition: contains(variables.apps, 'app_x')
  jobs:
  - job: Stage2Job1
    steps:
    - bash: echo "$(varT1) - $(varT2)"
```

```
variables:
  varT1: 'Variable value from template 1'
```

```
variables:
  varT2: 'Variable value from template 2'
```

**Comment by steved0x** [comment]
Another interesting thing I observed, in this section:

```
  condition: contains(variables.apps, 'app_x')
  jobs:
  - job: Stage2Job1
    steps:
    - bash: echo "$(varT1) - $(varT2)"
    - bash: echo $(apps)
```

This line `    - bash: echo $(apps)' produces and empty output unless I comment out the condition that first references that variable. Then it produces the desired output. That behavior seems unusual. Is there any other use of the `apps` variable in the stage or do you just use it for the condition?

**Comment by steved0x** [comment]
I made two more pipelines, using the same names as yours, so that if I missed something it would be more apparent. They both run both stages. I will still file a report describing the issue but if I can get a running example that has the same issue, that would be a great help. Thank you.

```
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: prepare
  jobs:
  - job: prepare_job
    steps:
    - bash: echo "##vso[task.setvariable variable=apps;isOutput=true]app_x present"
      name: ListApps
    - bash: echo $(ListApps.apps)

- stage: release_app_x
  dependsOn: prepare
  variables:
  - name: apps
    value: $[ dependencies.prepare.outputs['prepare_job.ListApps.apps'] ]
  - template: variables_template_1.yml
  - template: variables_template_2.yml
  condition: contains(variables.apps, 'app_x')
  jobs:
  - job: Stage2Job1
    steps:
    - bash: echo "$(varT1) - $(varT2)"
```

```
trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: prepare
  jobs:
  - job: prepare_job
    steps:
    - bash: echo "##vso[task.setvariable variable=apps;isOutput=true]app_x present"
      name: ListApps
    - bash: echo $(ListApps.apps)

- stage: release_app_x
  dependsOn: prepare
  variables:
  - template: variables_template_1.yml
  - template: variables_template_2.yml
  - name: apps
    value: $[ dependencies.prepare.outputs['prepare_job.ListApps.apps'] ]
  condition: contains(variables.apps, 'app_x')
  jobs:
  - job: Stage2Job1
    steps:
    - bash: echo "$(varT1) - $(varT2)"
```
