### ISSUE TITLE
ArchiveFiles@2 - Creating zip within zip

### ISSUE THREAD

**Issue by sandeepantony** [MicrosoftDocs/azure-devops-yaml-schema#105]
I'm trying to zip my publish directory using this task, but I'm zip inside another zip. 
Here is my task 
```
- task: ArchiveFiles@2
      displayName: 'Zip artifact'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)\deploy'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip
        replaceExistingArchive: true
        verbose: true
```
I'm expecting this...

- $(Build.BuildId).zip
    - {contents of deploy folder}

however this is what I get
- $(Build.BuildId).zip
    - deploy.zip
        - {contents of deploy folder}
