### ISSUE TITLE
Article doesn't mention applicationPackagePath can't end with \ or /

### ISSUE THREAD

**Issue by abatishchev** [MicrosoftDocs/azure-devops-yaml-schema#110]
Currently all the article says is this:

```yaml
- task: ServiceFabricUpdateManifests@2
  inputs:
    updateType: 'Manifest versions' # 'Manifest versions' | 'Docker image settings'. Required. Update Type. Default: Manifest versions.
    applicationPackagePath: # string. Required. Application Package.
```

and then:

```
applicationPackagePath - Application Package
string. Required.

Specifies the path to the application package. Variables and wildcards can be used in the path.
```

However, if `applicationPackagePath` had a trailing slash, i.e. ends with `\`, e.g.:

```yaml
applicationPackagePath: '$(RepoRoot)\${{ path.source }}\pkg\${{ parameters.configuration }}\'
                                                                                        # ^^^
```

Then the task fails with a generic error:

```
Searching for application package: C:\__w\1\s\src\Application\pkg\Release\
##[error]Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2c6177-5d9e-0aca-d6c9-e21036025eea
* Version Independent ID: 2a2c6177-5d9e-0aca-d6c9-e21036025eea
* Content: [ServiceFabricUpdateManifests@2 - Update Service Fabric manifests v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/service-fabric-update-manifests-v2?view=azure-pipelines)
* Content Source: [task-reference/service-fabric-update-manifests-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/service-fabric-update-manifests-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
