### ISSUE TITLE
Undocumented property for resources.containers.container definition

### ISSUE THREAD

**Issue by sliekens** [MicrosoftDocs/azure-devops-yaml-schema#115]
Hi,

It's possible to specify a `command` for a container resource definition, but this property is not documented.

Example azure-pipelines.yml

``` yaml
resources:
  containers:
    - container: minio
      image: minio/minio:latest
      command: server /data # <-- hidden feature?

services:
  minio: minio
```

It's unclear if this was a documentation oversight, or if this is the wrong way to pass additional arguments to the ENTRYPOINT of the container image.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1940f8b-486e-f1de-3447-125be89dae7c
* Version Independent ID: b1940f8b-486e-f1de-3447-125be89dae7c
* Content: [resources.containers.container definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container?view=azure-pipelines)
* Content Source: [content/resources-containers-container.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-containers-container.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
