### ISSUE TITLE
No possible values given for `lfs`, `submodules` & `persistCredentials`

### ISSUE THREAD

**Issue by jamiesandenr** [MicrosoftDocs/azure-devops-yaml-schema#12]
It's not very clear what values `lfs`, `submodules` and `persistCredentials` can take.  They are listed as having string values, but the description implies they really want to be boolean. Or, for instance, can `submodules` be `recursive`?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28abf7f-ecdf-8037-acd9-722690424372
* Version Independent ID: b28abf7f-ecdf-8037-acd9-722690424372
* Content: [steps.checkout definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines)
* Content Source: [content/steps-checkout.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-checkout.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@jamiesandenr You are correct, this isn't very clear. Here is some better information:
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#checkout-path

I will get this reference updated to match.

```
steps:
- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: boolean  # whether to fetch clean each time
  fetchDepth: number  # the depth of commits to ask Git to fetch
  lfs: boolean  # whether to download Git-LFS files
  submodules: true | recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
  path: string  # path to check out source code, relative to the agent's build directory (e.g. \_work\1)
  persistCredentials: boolean  # set to 'true' to leave the OAuth token in the Git config after the initial fetch
```
