### ISSUE TITLE
Incorrect pipeline resource metadata listed

### ISSUE THREAD

**Issue by Dilan-P** [MicrosoftDocs/azure-devops-yaml-schema#13]
The **pipeline resource metadata as predefined variables** lists `resources.pipeline.<Alias>.projectName` as an available predefined variable, however this variable does not resolve when trying to use it in a pipeline:

Attempting to output this variable using an example script task as follows;
```
resources:
  pipelines:
  - pipeline: myresourcevars  # identifier for the pipeline resource
    source: mypipeline # source pipeline definition name
    trigger: true 

steps:
- script: |
    echo $(resources.pipeline.myresourcevars.projectName)
```

results in the following output when running the pipeline:

```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\WINDOWS\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "C:\environments\someagent\_work\_temp\c3aee017-483c-43f6-b9f4-193b850e6601.cmd""
$(resources.pipeline.myresourcevars.projectName)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Version Independent ID: bb60190b-fc26-9eb2-70c3-a8b1a0227658
* Content: [resources.pipelines.pipeline definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-pipelines-pipeline?view=azure-pipelines)
* Content Source: [content/resources-pipelines-pipeline.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-pipelines-pipeline.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
