### ISSUE TITLE
UsePythonVersion says optional addToPath argument is required

### ISSUE THREAD

**Issue by Codym48** [MicrosoftDocs/azure-devops-yaml-schema#131]
The [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines) of the UsePythonVersion task says
```yaml
# Use Python version v0
# Use the specified version of Python from the tool cache, optionally adding it to the PATH.
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' # string. Required. Version spec. Default: 3.x.
    #disableDownloadFromRegistry: false # boolean. Disable downloading releases from the GitHub registry. Default: false.
    #allowUnstable: false # boolean. Optional. Use when disableDownloadFromRegistry = false. Allow downloading unstable releases. Default: false.
    #githubToken: # string. Optional. Use when disableDownloadFromRegistry = false. GitHub token for GitHub Actions python registry. 
    addToPath: true # boolean. Required. Add to PATH. Default: true.
  # Advanced
    architecture: 'x64' # 'x86' | 'x64'. Required. Architecture. Default: x64.
```

But it seems to work fine without `addToPath`, and many of the examples in the [surrounding documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/customize-python?view=azure-devops#use-a-specific-python-version) do not mention `addToPath`. Recommend updating the documentation to indicate that's an optional input.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 19f23c00-449e-a57d-66f6-ad06d43f9854
* Version Independent ID: 19f23c00-449e-a57d-66f6-ad06d43f9854
* Content: [UsePythonVersion@0 - Use Python version v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines)
* Content Source: [task-reference/use-python-version-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/use-python-version-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
