### ISSUE TITLE
jobs.deployment.environment.tags is erroneously described as if a sequence is allowed

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/azure-devops-yaml-schema#15]
Here's an example from the page:

```yaml
environment:                # create environment and/or record deployments
  name: string              # name of the environment to run this job on.
  resourceName: string      # name of the resource in the environment to record the deployments against
  resourceId: number        # resource identifier
  resourceType: string      # type of the resource you want to target.
  tags: string | [ string ] # tag names to filter the resources in the environment
```

https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-deployment-environment?view=azure-pipelines#examples-1

This is a bug logged in February 2021 and a promise from Microsoft that the docs will be fixed.

https://developercommunity.visualstudio.com/t/when-attempting-to-use-more-than-one-tag-to-limit/1073745

Yet, the pipeline still wouldn't run, reporting `A sequence was not expected` if an array of tags is used in `tags`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c87e26d-28b9-6475-5888-2c777f6f3cf6
* Version Independent ID: 6c87e26d-28b9-6475-5888-2c777f6f3cf6
* Content: [jobs.deployment.environment definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-deployment-environment?view=azure-pipelines#environment-name-resourcename-resourceid-resourcetype-tags)
* Content Source: [content/jobs-deployment-environment.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-deployment-environment.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
