### ISSUE TITLE
Please clarify why inputs have quotes around them sometimes but not others.

### ISSUE THREAD

**Issue by edwardskrod** [MicrosoftDocs/azure-devops-yaml-schema#153]
Looking at the examples, I'm super confused why the scriptType and scriptLocation have quotes around them sometimes but not others:

```
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: <Name of the Azure Resource Manager service connection>
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
```

```
- task: AzureCLI@2
  inputs:
    azureSubscription: <Azure_Resource_Manager_Service_Connection>
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    arguments: '$(AZURE_STORAGE_ACCOUNT) $(AZURE_STORAGE_KEY)'
    inlineScript: './scripts/publish.ps1 $1 $2'
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Version Independent ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Content: [AzureCLI@2 - Azure CLI v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
