### ISSUE TITLE
an example would be helpful to understand jobs.job.uses definition

### ISSUE THREAD

**Issue by kewalaka** [MicrosoftDocs/azure-devops-yaml-schema#159]
Some extra details would be useful to clarify the purpose of the 'uses' statement in job definitions, and how this relates to remote definitions referenced by the 'resources' statement.  My understanding follows

The uses statement allows you to explicitly refer to a resource in a job, which is required if the setting "Protect access to repositories in YAML pipelines" is set to the secure default ("on").

One useful situation is where you don't want to explicitly use the 'checkout' statement to check out the remote repository.  The other useful scenario looks to be where you want to explicitly reference an agent pool resource.  

With a bit of experimentation, the following worked for me.

Assume a resource definition has been declared by this:

```yaml
resources:
  repositories:
    - repository: terraform-modules
      type: git
      name: common-library-project/terraform-modules-repo
```

In order for the DevOps build service to create a System Access Token that is correctly scoped, you can either
1) explicitly checkout the repository, e.g.:

```yaml
  steps:
    - checkout: terraform-modules
```

2) specify the repository with the job 'uses' definition, e.g.:

```yaml
  jobs:
    - job: MyJobName
      uses:
        repositories:
          - "terraform-modules"
```

In both cases, when running the pipeline for the first time, you should see the request to "Permit" access to the protected resource (the remote repository "terraform-modules" in this case).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e79db04b-d247-72dd-21ab-bd88de685c66
* Version Independent ID: e79db04b-d247-72dd-21ab-bd88de685c66
* Content: [jobs.job.uses definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-uses?view=azure-pipelines)
* Content Source: [content/jobs-job-uses.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-job-uses.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
