### ISSUE TITLE
Example .yml is not a valid pipeline in Azure DevOps

### ISSUE THREAD

**Issue by newnativeabq** [MicrosoftDocs/azure-devops-yaml-schema#162]
Expected Results:

Select New Pipeline in Azure DevOps.  Connect pipeline to repository.  Copy and paste example.yml code supplied.  Modify variables with subscription values.  Pipeline succeeds.

Actual Results:

Copying the pipeline code, the Azure DevOps IDE immediately begins warning user of incorrect formatting.  Running pipeline produces error with no helpful message.

Suggest Fix:

Complete the example.yml file with a complete pipeline instead of a snippet that cannot be run.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 464cc7a1-0d4a-cb50-35d3-cea67792bdf0
* Version Independent ID: 464cc7a1-0d4a-cb50-35d3-cea67792bdf0
* Content: [AzureFileCopy@5 - Azure file copy v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v5?view=azure-pipelines)
* Content Source: [task-reference/azure-file-copy-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-file-copy-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by WilliamAntonRohm** [comment]
@newnativeabq -- Vinny, thank you for your feedback.  Please consider these resources:
- [Azure DevOps Services](https://azure.microsoft.com/support/devops/) 
- [Azure DevOps on Stack Overflow](https://stackoverflow.com/questions/tagged/azure-devops)

@steved0x -- Steve, please look into this issue.

**Comment by steved0x** [comment]
I've updated the article with a complete pipeline that includes the trigger, vmImage, and steps statements to make it a complete pipeline.

```
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: AzureFileCopy@5
  inputs:
    SourcePath: 'Readme.md'
    azureSubscription: 'MyAzureSubscription'
    Destination: 'AzureBlob'
    storage: 'MyStorage'
    ContainerName: 'MyContainerName'
  name: AzureFileCopy
  
- script: | 
    echo $(AzureFileCopy.StorageContainerUri)
    echo $(AzureFileCopy.StorageContainerSasToken)
```
