### ISSUE TITLE
the page doesn't appear to be fully documented

### ISSUE THREAD

**Issue by GreenBattery** [MicrosoftDocs/azure-devops-yaml-schema#187]
[Enter feedback here]

It is not clear where the artifacts to be published are sourced from. 

For example:
```yaml
      - task: PublishPipelineArtifact@1
        displayName: 'Publishing manifests as pipeline artifact'
        inputs:
          path: $(Build.Sourcesdirectory)/my-container-name/manifest/
          artifact: 'Manifests'
```
This task appears to work fine, and publishes what is specified in the `path` input as `Manifests`, but you could never come to this conclusion by reading the current documentation of this pipeline task.

Perhaps I'm mistaken in my understanding, or the documentation is incomplete. I'm not sure which.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c01cefb9-8cb3-58aa-d1d1-33de985e49e6
* Version Independent ID: c01cefb9-8cb3-58aa-d1d1-33de985e49e6
* Content: [PublishPipelineArtifact@1 - Publish Pipeline Artifacts v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines)
* Content Source: [task-reference/publish-pipeline-artifact-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/publish-pipeline-artifact-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
