### ISSUE TITLE
AzureStaticWebApp@0 keep changing the s (staging) folder owner and group

### ISSUE THREAD

**Issue by GGJason** [MicrosoftDocs/azure-devops-yaml-schema#188]
My azure pipeline run on private self-hosted agent (Ubuntu 18.04.6 LTS) keep getting the error:
![image](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/8362482/c8b71ed3-8cb4-4f1b-ae3d-2c7fe75cc39a)

And I found that the owner and group of s (staging) folder in  ".../work/193" are different.
![image](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/assets/8362482/f3d38014-9f4f-4713-b0e6-0102e316f140)

I change the owner and group and run the pipeline again. After the job finished, the permission changed again. 

Below is the pipeline yaml script,

``` yaml
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    name: Default
  variables:
  - group: Azure-Static-Web-Apps
  steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_SKY_0DAFD5400)
      app_location: "/" # App source code path
      api_location: ".output/server" # Api source code path - optional
      output_location: ".output/public" # Built app content directory - optional

```
