### ISSUE TITLE
Download Pipeline Artifact does not honor selected resources (triggering pipelines)

### ISSUE THREAD

**Issue by t-moe** [MicrosoftDocs/azure-devops-yaml-schema#205]
We have a pipeline with a resource trigger (other pipeline).
This pipeline has a task

```
 - task: DownloadPipelineArtifact@2
    displayName: Download Files
    inputs:
      buildType: 'specific'
      project: '...'
      definition: '...'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latestFromBranch'
      branchName: '$(Build.SourceBranch)'
      targetPath: '$(Build.SourcesDirectory)/Files'
      artifactName: 'Files'
      allowPartiallySucceededBuilds: true
```

Now, if I manually trigger this pipeline, I get a UI to select the resource version. Per default, it says "use latest version of all resources". 

If I select an older version there, the pipeline still downloads the newest version of the artifacts and not the ones I've selected....
While the wrong artifacts are downloaded (wrong build id visible in log of DownloadPipelineArtifact), the pipeline shows the correct "consumed artifacts" (correct build id).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Version Independent ID: 6d5753b5-d4e7-6696-0230-3595f632ba0e
* Content: [DownloadPipelineArtifact@2 - Download Pipeline Artifacts v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-pipeline-artifact-v2?view=azure-pipelines)
* Content Source: [task-reference/download-pipeline-artifact-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-pipeline-artifact-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
