### ISSUE TITLE
HelmDeploy@0 ingress controller installer sample

### ISSUE THREAD

**Issue by iamsoorya** [MicrosoftDocs/azure-devops-yaml-schema#210]
[Enter feedback here]
If you can provide the ingress controller installation sample would be very useful
I have the following but does not work.

- task: HelmInstaller@1
            displayName: Helm installer 3.12.2
            inputs: 
              helmVersionToInstall: 3.12.2
            env:
              HELM_EXPERIMENTAL_OCI: 1
- task: HelmDeploy@0
            displayName: 'K8S Ingress Controller deployment'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              azureResourceGroup: '${{ parameters.aks_rg }}'
              kubernetesCluster: '${{ parameters.aks_name }}'
              useClusterAdmin: true
              command: upgrade
              install: true
              chartType: Name
              chartVersion: '${{ parameters.k8s_ingress_chart_ver }}'
              namespace: '${{ parameters.ns_alps_ingress }}'
              chartName: "https://kubernetes.github.io/ingress-nginx/ingress-nginx"
              releaseName: "k8s-nginx"
              updatedependency: false
              force: true
              waitForExecution: true
              failOnStderr: true
              publishPipelineMetadata: true             
              valueFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.tfWorkingDir }}/values/01-ingress-nginx-helm-config.yaml'
              arguments: '--debug'
            env:
             HELM_EXPERIMENTAL_OCI: 1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf86a234-e187-12d4-5195-c80fbadf25b2
* Version Independent ID: bf86a234-e187-12d4-5195-c80fbadf25b2
* Content: [HelmDeploy@0 - Package and deploy Helm charts v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/helm-deploy-v0?view=azure-pipelines)
* Content Source: [task-reference/helm-deploy-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/helm-deploy-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by iamsoorya** [comment]
I have found a solution. The argument parameter allows use add all missing options of helm
The HelmDeploy task should look like below: 
```yaml
- task: HelmDeploy@0
            displayName: 'K8S Ingress Controller deployment'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              azureResourceGroup: '${{ parameters.aks_rg }}'
              kubernetesCluster: '${{ parameters.aks_name }}'
              useClusterAdmin: true
              command: upgrade
              install: true
              chartType: Name
              chartVersion: '${{ parameters.k8s_ingress_chart_ver }}'
              namespace: '${{ parameters.ns_alps_ingress }}'
              chartName: 'ingress-nginx' # "https://kubernetes.github.io/ingress-nginx/ingress-nginx"
              releaseName: "k8s-nginx"
              updatedependency: false
              force: true
              waitForExecution: true
              failOnStderr: false
              ##recreate: true  deprecated
              publishPipelineMetadata: true             
              valueFile: '$(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.tfWorkingDir }}/values/01-ingress-nginx-helm-config.yaml'
              arguments: '--debug --atomic --timeout 120s --repo https://kubernetes.github.io/ingress-nginx '
            env:
             HELM_EXPERIMENTAL_OCI: 1
```
