### ISSUE TITLE
Type of `jobs.job.strategy.parallel`

### ISSUE THREAD

**Issue by afscrome** [MicrosoftDocs/azure-devops-yaml-schema#227]
The docs for `strategy: parallel` say `strategy.parallel` is of type `string`

```yaml
strategy:
  parallel: string # Run the job this many times.
```

However in the example, the value is given as `4` (which is a `number`)
```yaml
jobs:
- job: SliceItFourWays
  strategy:
    parallel: 4 # <--- The earlier docs said this was `string`, but `4` is a `number`
```

Should the docs say that `strategy.parallel` is of type `number`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38aa6313-3818-cb19-e06d-8e52364f992b
* Version Independent ID: 38aa6313-3818-cb19-e06d-8e52364f992b
* Content: [jobs.job.strategy definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines)
* Content Source: [content/jobs-job-strategy.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-job-strategy.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
