### ISSUE TITLE
Missing docs on "name" property

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/azure-devops-yaml-schema#245]
This doc says you can set the build number using the `name` property: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml

example:

```yaml
name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)

steps:
  - script: echo '$(Build.BuildNumber)' # outputs customized build number like project_def_master_20200828.1
```

However, these yaml referece docs don't contain any info on this `name` property, making it harder to find the above docs where it is documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Version Independent ID: 9316a0c0-9ccb-7bca-390f-771c9baa4e8d
* Content: [YAML schema reference](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/?view=azure-pipelines)
* Content Source: [content/index.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/index.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
