### ISSUE TITLE
How to pass system variables to container job?

### ISSUE THREAD

**Issue by ezlee** [MicrosoftDocs/azure-devops-yaml-schema#254]
In the container job 
```
     container:
        image: dockerhub.io/myregistry/myimg:latest 
        options: --privileged --volume '$(System.DefaultWorkingDirectory)':/mnt/data:ro
     steps:
     - script: printenv
```
How do I use the $System.DefaultWorkingDirectory variable so that I can mount the source code directory into the /mnt/data mounting point in the container?

I tried multiple ways, it always complaining using invalid characters. 
`Error response from daemon: create '$(System.DefaultWorkingDirectory)': "'$(System.DefaultWorkingDirectory)'" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`

thanks!
