### ISSUE TITLE
Incorrect schema for container resources

### ISSUE THREAD

**Issue by shubham1172** [MicrosoftDocs/azure-devops-yaml-schema#297]
Under https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container-trigger?view=azure-pipelines#examples-1, the schema mentioned is

```yaml
resources:         
  containers:
  - container: petStore      
    type: ACR  
    azureSubscription: ContosoARMConnection
    resourceGroup: ContosoGroup
    registry: petStoreRegistry
    repository: myPets
    trigger: 
      tags: true # This is incorrect!
```

The actual schema can be found here https://learn.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=schema#define-a-containers-resource, which makes it

```yaml
resources:         
  containers:
  - container: petStore      
    type: ACR  
    azureSubscription: ContosoARMConnection
    resourceGroup: ContosoGroup
    registry: petStoreRegistry
    repository: myPets
    trigger: 
      enabled: true # This is correct!
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67c2a635-dc84-b34d-dddc-b1fab3bd335a
* Version Independent ID: 67c2a635-dc84-b34d-dddc-b1fab3bd335a
* Content: [resources.containers.container.trigger definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-containers-container-trigger?view=azure-pipelines#triggerstring)
* Content Source: [content/resources-containers-container-trigger.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/resources-containers-container-trigger.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
