### ISSUE TITLE
Demonstrate mapping parameters into variable template

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/azure-devops-yaml-schema#30]
This page mentions being able to pass parameters into the variable template, but the examples don't include that usage.  I think it would be very helpful to include examples which might demonstrate syntax, and perhaps suggest proper use-cases and caveats to watch out for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0faddf7-59db-3923-66c7-c720ce9833bf
* Version Independent ID: e0faddf7-59db-3923-66c7-c720ce9833bf
* Content: [variables.template definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/variables-template?view=azure-pipelines)
* Content Source: [content/variables-template.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/variables-template.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@ronwarner You have probably seen these already:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#variable-reuse

Let me see if I can get some better examples from our writer that owns variables and templates, and I'll get this page updated.

Thank you for the feedback!

**Comment by steved0x** [comment]
#reassign juliakm

**Comment by juliakm** [comment]
@ronwarner Here's a small example that's a bit simpler than the one in the docs. I've reviewed the variables article and I think that the current example should work for most scenarios. I'll add a link to the article from the schema page. 

```yaml
# File: package-release-with-params.yml
parameters:
- name: coffeetype 
  type: string
  default: "decaf" 

variables:
- name: makecoffee
  value: brewing ${{ parameters.coffeeType }} 


```

```yaml
# File: azure-pipelines.yml

variables:
  - template: package-release-with-params.yml # Template reference
    parameters:
      coffeetype: "drip"

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: A 
  variables: # Stage variables
  - template: package-release-with-params.yml  # Template reference
    parameters:
      coffeetype: "espresso latte"
  jobs: 
  - job: A
    steps: 
    - bash: $(makecoffee) #output release command
```
