### ISSUE TITLE
Does the environment specification support any user-defined variables?

### ISSUE THREAD

**Issue by carlin-q-scott** [MicrosoftDocs/azure-devops-yaml-schema#306]
Does the environment specification support any user-defined variables? I don't see any mention of it not supporting user-defined variables, but I get this error when I try to use pipeline/stage variables from my pipeline:

> Environment name cannot contain resourceName 'environment ]' if resourceName is explicitly specified '$[ variables['VM.Name'] ]

pipeline.yml:
```yaml
variables:
  environment: Test
  VM.Name: MyTestVM
jobs:
  - deployment: DeployCoreAPI
    displayName: Deploy Core API to $(environment)
    dependsOn: PrepareDeploy
    environment:
      name: $[ variables.environment ]
      resourceType: VirtualMachine
      resourceName: $[ variables['VM.Name'] ]
```

It seems like it's not resolving the variables and failing. It is a compile time error too, so I suspect it doesn't support variables for that reason as well. I'd expect it to fail on initiating the job if it did support user-defined variables.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c87e26d-28b9-6475-5888-2c777f6f3cf6
* Version Independent ID: 6c87e26d-28b9-6475-5888-2c777f6f3cf6
* Content: [jobs.deployment.environment definition](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-deployment-environment?view=azure-pipelines)
* Content Source: [content/jobs-deployment-environment.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/jobs-deployment-environment.md)
* Service: **azure-devops-pipelines**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
