### ISSUE TITLE
Xcode@5 does not correctly escape device parameter

### ISSUE THREAD

**Issue by joshuapoq** [MicrosoftDocs/azure-devops-yaml-schema#320]
When using this task the destination argument isn't being surrounded by quotes causing xcodebuild to incorrectly match the full list of devices and choose the first. This seems like quite a big issue so I'm surprised it's not come up before.

## Config
I have our YAML pipelines set up with the following:
```yml
- task: Xcode@5
  displayName: Validate ${{ parameters.xcodeScheme }}
  inputs:
    actions: ${{ parameters.xcodeActions }}
    configuration: ${{ parameters.xcodeConfiguration }}
    sdk: iphonesimulator
    xcWorkspacePath: ${{ parameters.xcodeWorkspace }}
    scheme: ${{ parameters.xcodeScheme }}
    xcodeVersion: specifyPath
    xcodeDeveloperDir: ${{ parameters.xcodeDeveloperDir }}
    signingOption: default
    destinationPlatformOption: iOS
    destinationSimulators: $(Agent.Name)
    publishJUnitResults: true
```

Note: I've simplified some of the paths and cut out some info in the below examples.

## Output
This runs the following:
```
/usr/bin/xcodebuild -configuration Debug -workspace Project.xcworkspace -scheme SomeScheme -destination platform=iOS Simulator,name=MacMini-M2-2 test
```
Which results in the following output at the top of running (I'm only pasting the important bits):
```
Build settings from command line:
    Simulator,name = MacMini-M2-2

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, variant:Designed for [iPad,iPhone], id:00008112-000D59DC3681A01E }
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:DA3948D6-B95D-4487-AB15-0CF4E8D80328, OS:17.2, name:MacMini-M2-2 }
{ platform:iOS Simulator, id:DA3948D6-B95D-4487-AB15-0CF4E8D80328, OS:17.2, name:MacMini-M2-2 }
```

## Expectation
I expect this command instead which works with the quotes:
```
/usr/bin/xcodebuild -configuration Debug -workspace Project.xcworkspace -scheme SomeScheme -destination "platform=iOS Simulator,name=MacMini-M2-2" test
```
Output:
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:DA3948D6-B95D-4487-AB15-0CF4E8D80328, OS:17.2, name:MacMini-M2-2 }
{ platform:iOS Simulator, id:DA3948D6-B95D-4487-AB15-0CF4E8D80328, OS:17.2, name:MacMini-M2-2 }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32f37803-2465-bc77-b00b-1530ce74ee35
* Version Independent ID: 32f37803-2465-bc77-b00b-1530ce74ee35
* Content: [Xcode@5 - Xcode v5 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/xcode-v5?view=azure-pipelines)
* Content Source: [task-reference/xcode-v5.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/xcode-v5.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
