### ISSUE TITLE
Wrong principal used for access to keyvault AzureKeyVault@2

### ISSUE THREAD

**Issue by ferronsw** [MicrosoftDocs/azure-devops-yaml-schema#39]
I'm running a self-host ubuntu 20.04 Azure DevOps agent on my AKS cluster with Azure Workload Identity.
In a job I have specified the following:

``` 
    - task: AzureKeyVault@2
      displayName: Get password
      inputs:
        azureSubscription: 'Azure Subscription'
        KeyVaultName: 'kv-pipeline'
        SecretsFilter: 'dev-postgress-admin-password'
        RunAsPreJob: false
```

The self-hosted agent doesn't use the 'azureSubscription' service principal connection to connect to the keyvault, but the AKS managed identity. I didn't expect this to happen. I would expect the self hosted agent to use the Azure Devops service principal.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16afc034-bd8e-2263-4af0-aef56e66d916
* Version Independent ID: 16afc034-bd8e-2263-4af0-aef56e66d916
* Content: [AzureKeyVault@2 - Azure Key Vault v2 task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-key-vault-v2?view=azure-pipelines#output-variables)
* Content Source: [task-reference/azure-key-vault-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-key-vault-v2.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
