### ISSUE TITLE
Missing documentation on Task behaviour and scope - Whether it fails if a test fails, and whether it always publishes test results.

### ISSUE THREAD

**Issue by Geraint-Davies** [MicrosoftDocs/azure-devops-yaml-schema#57]
I'm looking for the default behaviour if a single test fails in this Test task. 

Does it fail the task? (e.g. in an ARM template, in a task after this one, would succeeded() in a condition return false?)
```
condition: and(succeeded(), ne(variables.test, false))
```

Would the Build fail? It appears to but I can't see this documented anywhere.

It also looks like test results are always published, and there's no need for the PublishTestResults@2 task. But I can't find confirmation yes/no of this either. Even if this _is_ implicitly included under the VSTest@2 task, it has a property of `failTaskOnFailedTests` but this defaults to false so I'm still stumped.

My ARM template task:
```
- task: VSTest@2
  displayName: Test
  inputs:
	testSelector: 'testAssemblies'
	searchFolder: src\$(srcPath)\Tests
	testAssemblyVer2: |
	  **\bin\Debug\*\$(namespace).Tests.*.dll
	  !**\$(namespace).Tests.Framework.dll
	  !**\obj\**
	vstestLocationMethod: location
	vstestLocation: $(TestPlatform)
	testRunTitle: '$(namespace) (all tests)'
	runSettingsFile: '$(Build.SourcesDirectory)\$(testFmwkPath)\$(testSettings)'
	codeCoverageEnabled: false
	publishRunAttachments: true
	failOnMinTestsNotRun: true
	minimumExpectedTests: '1'
	runInParallel: false
	platform: '$(buildPlatform)'
	configuration: Debug
  condition: and(succeeded(), ne(variables.test, false))
```
Pipeline:
![image](https://user-images.githubusercontent.com/104198629/203402924-2ae4c73e-c349-4ed9-9e2c-18388f9325fe.png)

Thanks!
Ger

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Version Independent ID: 5a378422-4758-62c7-1793-7ce4724079aa
* Content: [VSTest@2 - Visual Studio Test v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/vstest-v2?source=recommendations&view=azure-pipelines)
* Content Source: [task-reference/vstest-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/vstest-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
