### ISSUE TITLE
Docs for access service principal details in script for AzureCLI@2 task

### ISSUE THREAD

**Issue by KarenTazayan** [MicrosoftDocs/azure-devops-yaml-schema#61]
Please add this case into documentation:

When we use option **addSpnToEnvironment: true** in Linux with bash for Azure CLI command parameters we have to use this syntax (environment variable with runtime expression syntax):

```yml
paramName=${servicePrincipalId}
```
instead of

```yml
paramName=$servicePrincipalId
```
For example:

```yml
- task: AzureCLI@2
      displayName: 'Deploy the whole infrastructure to Azure'
      inputs:
        azureSubscription: 'DefaultAzureServiceConnection'
        addSpnToEnvironment: true
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create --name $(resourceGroupName)-$(nameSuffix) --location $(location)
          az deployment group create --resource-group $(resourceGroupName)-$(nameSuffix) \
             --template-file $(templateFile) --parameters nameSuffix='$(nameSuffix)' \
             appNamePrefix='$(appNamePrefix)' semVer='$(GitVersion.SemVer)' sqlAdministratorPassword='Pass' \
             acrUrl='$(acrUrl)' acrLogin='$(acrLogin)' acrPassword='$(acrPassword)' \
             executorSecurityPrincipal=${servicePrincipalId}
```

Otherwise, it won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Version Independent ID: 3ed2fb7c-dd4c-7d2a-a934-e86bc5c1aa5d
* Content: [AzureCLI@2 - Azure CLI v2 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines)
* Content Source: [task-reference/azure-cli-v2.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/azure-cli-v2.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
