### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client (*).

### ISSUE THREAD

**Issue by dermoritz** [MicrosoftDocs/azure-devops-yaml-schema#67]
If i try to acquire the very latest version/ snapshot of an artifact with:

i use ```*``` as documented [here](https://learn.microsoft.com/en-us/azure/devops/artifacts/quickstarts/universal-packages?view=azure-devops&tabs=azuredevops#downloading-the-latest-version)

```
- task: DownloadPackage@1
  inputs: 
    packageType: 'maven'
    feed: 'Artifacts'
    definition: 'package:artifact'
    version: '*'
    files: '*.jar'
    downloadPath: './target/'
```

the pipeline fails: A potentially dangerous Request.Path value was detected from the client (*).
```latest``` is not working because it matches all SNAPSHOTs from latest version.
So how to setup DownloadPackage to download latest Snapshot?

I also tried to set version explicitly to "0.0.1-snapshot" with same result: The task is downloading all snapshots and not only the latest. On the other hand: if maven is setup with dependency to "0.0.1-SNAPSHOT" it resolves exactly to the latest snapshot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 769d848b-315d-86bf-1673-5a87f87a970d
* Version Independent ID: 769d848b-315d-86bf-1673-5a87f87a970d
* Content: [DownloadPackage@1 - Download package v1 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/download-package-v1?view=azure-pipelines)
* Content Source: [task-reference/download-package-v1.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/download-package-v1.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
