### ISSUE TITLE
Where did the old Task spec/schema go?

### ISSUE THREAD

**Issue by FilBot3** [MicrosoftDocs/azure-devops-yaml-schema#7]
# Where is the actual spec/schema

Prior to the change in the layout of Azure Pipelines YAML "schema" trying to look like the C#-styled docs, there was an actual schema or specification as to what the Task looked like. Where did that go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009defbf-5bfc-9375-72f0-6df3f7bb03b5
* Version Independent ID: 009defbf-5bfc-9375-72f0-6df3f7bb03b5
* Content: [steps.task definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-task?view=azure-pipelines)
* Content Source: [content/steps-task.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/content/steps-task.md)
* Product: **devops**
* Technology: **devops-cicd**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by steved0x** [comment]
@FilBot3 You can still view the old schema here:

https://web.archive.org/web/20211130113026/https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#task

For task, do you mean the common items that are the same for all tasks, apart from the inputs? 

```
steps:
- task: string  # reference to a task and version, e.g. "VSBuild@1"
  displayName: string  # friendly name displayed in the UI
  name: string  # identifier for this step (A-Z, a-z, 0-9, and underscore)
  condition: string
  continueOnError: boolean  # 'true' if future steps should run even if this step fails; defaults to 'false'
  enabled: boolean  # whether to run this step; defaults to 'true'
  retryCountOnTaskFailure: number # Max number of retries; default is zero
  target:
    container: string # where this step will run; values are the container name or the word 'host'
    commands: enum  # whether to process all logging commands from this step; values are `any` (default) or `restricted`
    settableVariables: string # what variables are allowed; defaults to all; can be `none` or a list of allowed vars
  timeoutInMinutes: number
  inputs: { string: string }  # task-specific inputs
  env: { string: string }  # list of environment variables to add
```

I can update the task page to include this information, and the reference will be updated with more tasks information coming soon.

The old page was just getting too big to manage, and since the framework was there to automate the structure (and much of the content), we modeled it after our other reference docsets,
