### ISSUE TITLE
Azure Pipelines: Error: Unable to locate executable file: 'docker'

### ISSUE THREAD

**Issue by NivGreenstein** [MicrosoftDocs/azure-devops-yaml-schema#86]
Hey! 
I'm trying to use this tool by installing it on VMSS as agent pool in Azure Devops Pipelines. 
Unfortunately, I get this error:

```
Starting: DockerInstaller
==============================================================================
Task         : Docker CLI installer
Description  : Install Docker CLI on agent machine.
Version      : 0.214.0
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-installer-tsg
==============================================================================
Downloading: https://download.docker.com/linux/static/stable/x86_64/docker-17.09.0-ce.tgz
Extracting archive
/usr/bin/tar xC /agent/_work/_temp/2520bd68-2b80-4eac-a7f3-1e9da085c7d9 -f /agent/_work/_temp/docker-16e10129-3ea4-4d4e-8140-0a6057ed4072.tgz
Caching tool: docker-stable 17.9.0-ce x64
Prepending PATH environment variable with directory: /agent/_work/_tool/docker-stable/17.9.0-ce/x64
Verifying docker installation...
##[error]Error: Unable to locate executable file: 'docker'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
Finishing: DockerInstaller
```
My azure pipeline yaml:
```
trigger:
  - main

pool:
  name: 'VMSSAgentPool'

steps:
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  - task: Docker@2
    inputs:
      containerRegistry: 'myacr'
      repository: 'myimage'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93ac37cc-abab-5bfd-d78d-8843d96a14da
* Version Independent ID: 93ac37cc-abab-5bfd-d78d-8843d96a14da
* Content: [DockerInstaller@0 - Docker CLI installer v0 task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-installer-v0?view=azure-pipelines&viewFallbackFrom=azure-devops)
* Content Source: [task-reference/docker-installer-v0.md](https://github.com/MicrosoftDocs/azure-devops-yaml-schema/blob/main/task-reference/docker-installer-v0.md)
* Service: **azure-devops-pipelines**
* Sub-service: **azure-devops-pipelines-tasks**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**
